# Site settings
title: Ahmed Abdelaal
email: ahmed@fitucated.com
name: "Ahmed Abdelaal"
description: "Full Stack Ruby on Rails Developer"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://WebAhmed.github.io" # the base hostname & protocol for your site

sass:
  sass_dir: assets/css
  style: :nested

# Tags (tag cloud)
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# Social Media
twitter_username: Z1ahmed
github_username:  WebAhmed

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
plugins: [jekyll-paginate]
port: 3000
