# Site settings
title: Ahmed Abdelaal
email: ahmed@fitucated.com
name: ""
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://WebAhmed.github.io" # the base hostname & protocol for your site
sass:
  sass_dir: assets/css
  style: :nested

# Social Media
twitter_username: Z1ahmed
github_username:  WebAhmed

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10

port: 3000
